apiVersion: v1
kind: ConfigMap
metadata:
  name: evidence-config
  namespace: pmp-evidence
  labels:
    app.kubernetes.io/name: evidence
    app.kubernetes.io/part-of: pmp
data:
  EVIDENCE_DB_HOST: postgres.pmp-data.svc.cluster.local
  EVIDENCE_DB_PORT: "5432"
  EVIDENCE_DB_NAME: evidence_db
  EVIDENCE_DB_OWNER_USER: evidence_owner
  EVIDENCE_DB_APP_USER: evidence_app
  EVIDENCE_IAM_JWKS_URL: http://iam.pmp-iam.svc.cluster.local:8001/api/v1/auth/jwks
  EVENTS_KAFKA_BOOTSTRAP: kafka.pmp-data.svc.cluster.local:9092
  EVENTS_TOPIC_PREFIX: ""
  EVIDENCE_JWT_ISSUER: "pmp-iam-service"
  EVIDENCE_JWKS_CACHE_TTL: "300"
