apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-config
  namespace: pmp-iam
  labels:
    app.kubernetes.io/name: iam
    app.kubernetes.io/part-of: pmp
data:
  IAM_DB_HOST: postgres.pmp-data.svc.cluster.local
  IAM_DB_PORT: "5432"
  IAM_DB_NAME: identity_db
  IAM_DB_USER: iam_service
  EVENTS_KAFKA_BOOTSTRAP: kafka.pmp-data.svc.cluster.local:9092
  EVENTS_TOPIC_PREFIX: ""
  IAM_JWT_ISSUER: "pmp-iam-service"
  IAM_JWT_KID: "iam-prod-1"
  IAM_ACCESS_TOKEN_TTL: "900"
  IAM_REFRESH_TOKEN_TTL: "604800"
  IAM_MAX_FAILED_LOGINS: "5"
  IAM_PASSWORD_MIN_LENGTH: "12"
  IAM_MFA_ISSUER_LABEL: "PMP"
